### ISSUE TITLE
spaceStatus and pwrStatus ERROR not working

### ISSUE THREAD

**Issue by jaedwards24** [kc9wwh/macOSUpgrade#113]
https://github.com/kc9wwh/macOSUpgrade/blob/326a5bce0a530746ad77b1443ff05f08ed0b07e7/macOSUpgrade.sh#L376

In my testing, Macs that have a spaceStatus=ERROR are not getting the "Requirements Not Met" jamfHelper dialog. Instead, the logs show the "Disk Check: ERROR" and free space amount before proceeding to attempt the upgrade. I do not believe that pwrStatus=ERROR was causing the "Requirements Not Met" dialog either. 

I changed line 376 to the following and believe it's working as expected:
`if ! { [ ${pwrStatus} == "OK" ] && [ ${spaceStatus} == "OK" ]; }; then`

I'm completely new to Github so I apologize if I'm reporting this incorrectly.

**Comment by kenchan0130** [comment]
@jaedwards24 
Thank you for your report.

```sh
bash-3.2$ pwrStatus="ERROR"
bash-3.2$ if ! [[ ${pwrStatus} == "OK" ]] && [[ ${spaceStatus} == "OK" ]]; then
  echo 'true'
else
  echo 'false'
fi

false
```

As you said, there seems to be a problem with that part.
I will prepare a patch from now on.

**Comment by kenchan0130** [comment]
@jaedwards24 
This has been fixed.
Thank you for your contribution!
