### ISSUE TITLE
macOS Mojave upgrade fails due to lack of space even though it passed the 15GB system check

### ISSUE THREAD

**Issue by adammartin253** [kc9wwh/macOSUpgrade#117]
Came across a Mac that had about 17GB of free space so it made it past the pre-check but once it began the actual in-place upgrade it fails to complete due to lack of storage space.

I removed a few GB to get to 21GB free and tried again. This time I was successful. To avoid this, I am suggesting to change the following parameter on https://github.com/kc9wwh/macOSUpgrade/blob/e193c61d83b51e1d0d89a6b93156e25f4b1d9a3c/macOSUpgrade.sh#L217, https://github.com/kc9wwh/macOSUpgrade/blob/e193c61d83b51e1d0d89a6b93156e25f4b1d9a3c/macOSUpgrade.sh#L226 and https://github.com/kc9wwh/macOSUpgrade/blob/e193c61d83b51e1d0d89a6b93156e25f4b1d9a3c/macOSUpgrade.sh#L377 are as so:

##Check if free space > 20GB

if [[ ${freeSpace%.*} -ge 20000000000 ]]; then

    /Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType utility -title "$title" -icon "$icon" -heading "Requirements Not Met" -description "We were unable to prepare your computer for $macOSname. Please ensure you are connected to power and that you have at least 20GB of Free Space.

**Comment by kenchan0130** [comment]
@adammartin253 
Thank you for your feedback.
I will fix this issue.

Please tell us which version you upgraded to which version.

**Comment by adammartin253** [comment]
Mac OS X 10.11.6 to macOS Mojave 10.14.4

Adam Martin
HBO Desktop Engineer – Media Technology & Information Services


On Jun 10, 2019, at 7:57 PM, Tadayuki Onishi <notifications@github.com<mailto:notifications@github.com>> wrote:

**External Email received from: noreply@github.com<mailto:noreply@github.com> **


@adammartin253<https://github.com/adammartin253>
Thank you for your feedback.
I will fix this issue.

Please tell us which version you upgraded to which version.

**Comment by kenchan0130** [comment]
@adammartin253 
I would say this issue was fixed. If you still have problems, please reopen.

**Comment by adammartin253** [comment]
Looks good to me

Sent from my iPhone

On Jun 12, 2019, at 11:44 PM, Tadayuki Onishi <notifications@github.com<mailto:notifications@github.com>> wrote:

**External Email received from: noreply@github.com<mailto:noreply@github.com> **


@adammartin253<https://github.com/adammartin253>
I would say this issue was fixed. If you still have problems, please reopen.
