### ISSUE TITLE
Post upgrade recon not working

### ISSUE THREAD

**Issue by Coros** [kc9wwh/macOSUpgrade#141]
All of our devices report as the old OS version after running an upgrade through this script.  In mojave I had added my own first boot script (through outset) and it solved the issue.  That work around isn't working on the Catalina upgrade.

The recon may be running, but I think it's prior to the upgrade completing so an old version is reported.

**Comment by arekdreyer** [comment]
I'm playing with the following in the first boot script, but I'm not sure where to put the content of the echo that says we are waiting. /usr/local/jamfps/firstbootupgrade.log? Then that would get removed after waiting.

```
## Wait until /var/db/.AppleUpgrade disappears
while [ -e /var/db/.AppleUpgrade ];
do
	echo "\$(date "+%a %h %d %H:%M:%S"): Waiting for /var/db/.AppleUpgrade to disappear." >> /usr/local/jamfps/firstbootupgrade.logg
    sleep 60
done
    
## Wait until the upgrade process completes
INSTALLER_PROGRESS_PROCESS=\$(pgrep -l "Installer Progress")
until [ "\$INSTALLER_PROGRESS_PROCESS" = "" ];
do
	echo "\$(date "+%a %h %d %H:%M:%S"): Waiting for Installer Progress to complete." >> /usr/local/jamfps/firstbootupgrade.log
    sleep 60
    INSTALLER_PROGRESS_PROCESS=\$(pgrep -l "Installer Progress")
done
```
