### ISSUE TITLE
Unable to verify OS (Fullscreen Splashback)

### ISSUE THREAD

**Issue by master-vodawagner** [kc9wwh/macOSUpgrade#143]
This isn't an issue with your script but wonder if there could be a mechanism that cancels the process if startosinstall reports back an error "Unable to Verify OS)?

Launching startosinstall manually I can see the percentage increase but occasionally it will stop and report Unable to verify.  This will leave the fullscreen splash hanging indefinitely if its encountered

**Comment by master-vodawagner** [comment]
Any thoughts?

**Comment by kc9wwh** [comment]
Hey @master-vodawagner - 

Although I do see your point here, I think this is best filed as a bug with Apple. Yes, we could add a function to loop and scrape logs and look for if this were to fail, but it would introduce additional overhead as well as create additional issues. 

The script is using the `--pidtosignal` switch as specified for the `startosinstall` binary. However, when the binary fails to complete successfully it is not running that switch. This script does complete before the `startosinstall` binary is finished. This is also done on purpose to ensure a clean exit prior to `startosinstall` issuing a restart.
