### ISSUE TITLE
Sample copy for Self Service

### ISSUE THREAD

**Issue by syoung-quizlet** [kc9wwh/macOSUpgrade#144]
I wanted to add this but I didn't have permission.  For those wanting the self service description...

**Example of Required Self Service Description**

This process will upgrade your Mac to MacOS Catalina 10.15.4.

*Before proceeding...*
* Please ensure __all work is saved__
* Close any apps you may have open

_This process will take 30-90 minutes to complete, during which time you will not be able to use your Mac._

**Example of Factory Reset Self Service Description**

This process will erase and re-install MacOS Catalina 10.15.4 on your Mac.

*Before proceeding...*
* Please ensure __all work is saved__
* Close any apps you may have open

_This process will take 30-90 minutes to complete, during which time you will not be able to use your Mac._

**Comment by kc9wwh** [comment]
Hi @syoung-quizlet - 

If you submit a pull request with this either added to the readme or as a separate file we can certainly get this added! Submitting a pull request will also show you as a contributor then 😃

**Comment by syoung-quizlet** [comment]
Thanks.  I think I tried but it said I didn't have permission.  I must not be doing something right.  I'll try again.

*Sean Young*
IT Manager @ Quizlet

**Comment by kc9wwh** [comment]
Hey @syoung-quizlet - 

You should be able to just fork the repo to your account and once you've made the change, create a pull request to the master branch here.

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

Let us know if you continue to have issues and thank you for contributing!

**Comment by syoung-quizlet** [comment]
Ahh gotcha. Thanks.

*Sean Young*
IT Manager @ Quizlet

**Comment by syoung-quizlet** [comment]
Did I do this correctly?  Thanks for the info.  I've only done code changed internally.

https://github.com/kc9wwh/macOSUpgrade/pull/145

*Sean Young*
IT Manager @ Quizlet

**Comment by kc9wwh** [comment]
Perfect!
