### ISSUE TITLE
Not enough space, requirement not met

### ISSUE THREAD

**Issue by lrhodes80** [kc9wwh/macOSUpgrade#146]
I am attempting to use the script to erase install on a physical test machine. The machine is running 10.15.4. I am trying to erase and re-install 10.15.4. It is an iMac Retina 5K, 27 inch, 2017 model. Each time I try to run the policy from Jamf Self Service it brings up the "Requirement not met" Window saying I do not have enough space. However, I have 800 GB available.

![Screenshot 2020-05-04 at 12 56 01](https://user-images.githubusercontent.com/13626507/80963799-97263400-8e07-11ea-9506-8fec115dcf13.png)

**Comment by kc9wwh** [comment]
Hey @lrhodes80 -

Sorry to hear you are having issues. Can you provide a copy of the policy logs from Jamf Pro for this failure? 

Also, please run the below commands on that computer and provide the output.
```
/usr/bin/pmset -g ps
/usr/sbin/diskutil info -plist /
```

Thank you!
~Rosko

**Comment by lrhodes80** [comment]
Hey Rosko,

No worries, happy to help. I have attached the policy logs and when running


/usr/bin/pmset -g ps

I get ‘Now drawing from AC Power’

But when I run:


/usr/sbin/diskutil info -plist /

I get ‘Could not find disk: -plist’

Hope that helps?

Leo Rhodes
Principal Apple Engineer
Jamf-Pro & macOS Certified 
Bournemouth University / IT Services

**Comment by lrhodes80** [comment]
Sorry, here are the screen shots:

Leo Rhodes
Principal Apple Engineer
Jamf-Pro & macOS Certified 
Bournemouth University / IT Services

**Comment by kc9wwh** [comment]
Hey @lrhodes80 - 

You should get something like this with the `diskutil` command, this was taken on a 10.15.4 system.
```
josh.roskos@MarvinsDepressedMBP:~$ diskutil info -plist /
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>AESHardware</key>
	<true/>
	<key>APFSContainerFree</key>
	<integer>16681766912</integer>
	<key>APFSContainerReference</key>
	<string>disk1</string>
	<key>APFSContainerSize</key>
	<integer>499963174912</integer>
	<key>APFSPhysicalStores</key>
	<array>
		<dict>
			<key>APFSPhysicalStore</key>
			<string>disk0s2</string>
		</dict>
	</array>
	<key>APFSVolumeGroupID</key>
	<string>E0BC7DAE-8745-403C-9199-9A4D85EA0C39</string>
	<key>Bootable</key>
	<true/>
	<key>BooterDeviceIdentifier</key>
	<string>disk1s2</string>
	<key>BusProtocol</key>
	<string>PCI-Express</string>
	<key>CanBeMadeBootable</key>
	<false/>
	<key>CanBeMadeBootableRequiresDestroy</key>
	<false/>
	<key>Content</key>
	<string>41504653-0000-11AA-AA11-00306543ECAC</string>
	<key>DeviceBlockSize</key>
	<integer>4096</integer>
	<key>DeviceIdentifier</key>
	<string>disk1s5</string>
	<key>DeviceNode</key>
	<string>/dev/disk1s5</string>
	<key>DeviceTreePath</key>
	<string>IODeviceTree:/PCI0@0/RP13@1D,4/ANS2@0/AppleANS2Controller</string>
	<key>DiskUUID</key>
	<string>BBC8DEC6-18BA-4E5D-B7B7-298E534126D6</string>
	<key>Ejectable</key>
	<false/>
	<key>EjectableMediaAutomaticUnderSoftwareControl</key>
	<false/>
	<key>EjectableOnly</key>
	<false/>
	<key>Encryption</key>
	<true/>
	<key>FileVault</key>
	<true/>
	<key>FilesystemName</key>
	<string>APFS</string>
	<key>FilesystemType</key>
	<string>apfs</string>
	<key>FilesystemUserVisibleName</key>
	<string>APFS</string>
	<key>FreeSpace</key>
	<integer>0</integer>
	<key>Fusion</key>
	<false/>
	<key>GlobalPermissionsEnabled</key>
	<true/>
	<key>IOKitSize</key>
	<integer>499963174912</integer>
	<key>IORegistryEntryName</key>
	<string>Macintosh HD</string>
	<key>Internal</key>
	<true/>
	<key>Locked</key>
	<false/>
	<key>MediaName</key>
	<string></string>
	<key>MediaType</key>
	<string>Generic</string>
	<key>MountPoint</key>
	<string>/</string>
	<key>ParentWholeDisk</key>
	<string>disk1</string>
	<key>PartitionMapPartition</key>
	<false/>
	<key>RAIDMaster</key>
	<false/>
	<key>RAIDSlice</key>
	<false/>
	<key>RecoveryDeviceIdentifier</key>
	<string>disk1s3</string>
	<key>Removable</key>
	<false/>
	<key>RemovableMedia</key>
	<false/>
	<key>RemovableMediaOrExternalDevice</key>
	<false/>
	<key>SMARTDeviceSpecificKeysMayVaryNotGuaranteed</key>
	<dict>
		<key>AVAILABLE_SPARE</key>
		<integer>100</integer>
		<key>AVAILABLE_SPARE_THRESHOLD</key>
		<integer>99</integer>
		<key>CONTROLLER_BUSY_TIME_0</key>
		<integer>0</integer>
		<key>CONTROLLER_BUSY_TIME_1</key>
		<integer>0</integer>
		<key>DATA_UNITS_READ_0</key>
		<integer>60162909</integer>
		<key>DATA_UNITS_READ_1</key>
		<integer>0</integer>
		<key>DATA_UNITS_WRITTEN_0</key>
		<integer>40637835</integer>
		<key>DATA_UNITS_WRITTEN_1</key>
		<integer>0</integer>
		<key>HOST_READ_COMMANDS_0</key>
		<integer>2583953062</integer>
		<key>HOST_READ_COMMANDS_1</key>
		<integer>0</integer>
		<key>HOST_WRITE_COMMANDS_0</key>
		<integer>966252020</integer>
		<key>HOST_WRITE_COMMANDS_1</key>
		<integer>0</integer>
		<key>MEDIA_ERRORS_0</key>
		<integer>0</integer>
		<key>MEDIA_ERRORS_1</key>
		<integer>0</integer>
		<key>NUM_ERROR_INFO_LOG_ENTRIES_0</key>
		<integer>0</integer>
		<key>NUM_ERROR_INFO_LOG_ENTRIES_1</key>
		<integer>0</integer>
		<key>PERCENTAGE_USED</key>
		<integer>2</integer>
		<key>POWER_CYCLES_0</key>
		<integer>92</integer>
		<key>POWER_CYCLES_1</key>
		<integer>0</integer>
		<key>POWER_ON_HOURS_0</key>
		<integer>890</integer>
		<key>POWER_ON_HOURS_1</key>
		<integer>0</integer>
		<key>TEMPERATURE</key>
		<integer>296</integer>
		<key>UNSAFE_SHUTDOWNS_0</key>
		<integer>36</integer>
		<key>UNSAFE_SHUTDOWNS_1</key>
		<integer>0</integer>
	</dict>
	<key>SMARTStatus</key>
	<string>Verified</string>
	<key>Size</key>
	<integer>499963174912</integer>
	<key>SolidState</key>
	<true/>
	<key>SupportsGlobalPermissionsDisable</key>
	<true/>
	<key>SystemImage</key>
	<false/>
	<key>TotalSize</key>
	<integer>499963174912</integer>
	<key>VolumeAllocationBlockSize</key>
	<integer>4096</integer>
	<key>VolumeName</key>
	<string>Macintosh HD</string>
	<key>VolumeSize</key>
	<integer>0</integer>
	<key>VolumeUUID</key>
	<string>BBC8DEC6-18BA-4E5D-B7B7-298E534126D6</string>
	<key>WholeDisk</key>
	<false/>
	<key>Writable</key>
	<false/>
	<key>WritableMedia</key>
	<true/>
	<key>WritableVolume</key>
	<false/>
</dict>
</plist>
```

Also, just an FYI that when you reply it goes to the Github issue which doesn't take attachments and upload them so I didn't get the screenshots of the policy logs.

**Comment by lrhodes80** [comment]
Hiya, ok cool so I have attached the following:

Output from both commands and policy log screenshot:

<img width="608" alt="Screenshot 2020-05-06 at 11 20 58" src="https://user-images.githubusercontent.com/13626507/81181716-c6be7300-8fa4-11ea-8edf-ef55402c96cc.png">
[diskutil info.plist.txt](https://github.com/kc9wwh/macOSUpgrade/files/4586964/diskutil.info.plist.txt)
![Screenshot 2020-05-06 at 11 23 33](https://user-images.githubusercontent.com/13626507/81181765-d8077f80-8fa4-11ea-9c30-f91194f933cc.png)

Thanks in advance....

**Comment by lrhodes80** [comment]
Hey Josh, any clues on this? Thanks.

Leo Rhodes
Principal Apple Engineer
Jamf-Pro & macOS Certified 
Bournemouth University / IT Services

**Comment by kc9wwh** [comment]
@lrhodes80 your plist looks fine. 

- Is this only happening on this specific computer? 
- Have you tried this on any other computers? 
- Do they succeed?

You can try running this:
```
diskInfoPlist=$(/usr/sbin/diskutil info -plist /)

/usr/libexec/PlistBuddy -c "Print :APFSContainerFree" /dev/stdin <<< "$diskInfoPlist" 2>/dev/null || /usr/libexec/PlistBuddy -c "Print :FreeSpace" /dev/stdin <<< "$diskInfoPlist" 2>/dev/null || /usr/libexec/PlistBuddy -c "Print :AvailableSpace" /dev/stdin <<< "$diskInfoPlist" 2>/dev/null
```

But I suspect it will come back correct. The only other thing I can think of is to put the script in "debug mode" by adding a `-x` to the first line as such `#!/bin/bash -x`

**Comment by lrhodes80** [comment]
Ok, so I started from scratch and got further than last time. Here’s the error I got this time round:

macOS Installer Downloaded 3 Times - Checksum is Not Valid Prompting user for error and exiting... 0

I left variable 7 blank though.

Leo Rhodes
Principal Apple Engineer
Jamf-Pro & macOS Certified 
Bournemouth University / IT Services

**Comment by kc9wwh** [comment]
@lrhodes80 are you sure there isn't a space in there? The first thing the function does is check if the variable is blank or not, if its not blank, even a space or a hidden character it will try to validate the checksum.

**Comment by kc9wwh** [comment]
@lrhodes80 is this working on other computers? This would help rule out if its a computer or configuration issue. 

I'm also opening a support ticket for you so we can try and get an engineer on the phone with you to go over the setup.

**Comment by lrhodes80** [comment]
Hi Josh, thanks so much for your help. I tried on a MacBook also and the same policy is just stuck as pending in the logs and stuck on executing in Self Service.

Leo Rhodes
Principal Apple Engineer
Jamf-Pro & macOS Certified 
Bournemouth University / IT Services

**Comment by lrhodes80** [comment]
I just checked and there’s no space. Thanks.

Leo Rhodes
Principal Apple Engineer
Jamf-Pro & macOS Certified 
Bournemouth University / IT Services

**Comment by kc9wwh** [comment]
Hey @lrhodes80, just wanted to confirm this has been resolved as it looks like that packaged version of the macOS installer was different than what was specified in the script parameters?

**Comment by lrhodes80** [comment]
Hey Josh, yes it worked like a dream, thanks for your help with this.

Leo Rhodes
Principal Apple Engineer
Jamf-Pro & macOS Certified 
Bournemouth University / IT Services
