### ISSUE TITLE
Checksum is Not Valid: Parameter 7 is Blank

### ISSUE THREAD

**Issue by MusicMaker81** [kc9wwh/macOSUpgrade#147]
Thanks for this script. I want to use this to upgrade to Catalina. When running the script it does run the trigger and downloads the macOS installer. 
It ends with an error.
Jamf reports: macOS Installer Downloaded 3 Times - Checksum is Not Valid

I left 'Paramater 7' Blank because I didn't want to verify the checksum. So why does it report that the checksum is not valid?
I also tried it by entering the right checksum but that also failed with the same error.

**Comment by Ret2lib** [comment]
You can fix this by changing
`if [ -n "$installESDChecksum" ]; then
`
to 
`if [ "$installESDChecksum" != "0" ]; then
`
and replace the empty value with 0 or to an actual hash if you want to use the feature.

**Comment by RiversideKid** [comment]
> You can fix this by changing
> `if [ -n "$installESDChecksum" ]; then `
> to
> `if [ "$installESDChecksum" != "0" ]; then `
> and replace the empty value with 0 or to an actual hash if you want to use the feature.

I have applied this change, both the code change and I replaced parameter 7 with a 0 and I still get "checksum is not valid."  is there another way I could bypass the checksum error?

**Comment by kc9wwh** [comment]
@RiversideKid there is most likely a syntax error somewhere in the script from modifications or how it was copied. However, if you want to disable the `checksum` check, you can try commenting out line 363 of the latest version. If that doesn't work, you'll also want to comment out lines 371-374, but just 363 should be fine.

**Comment by kylejericson** [comment]
I have tried the line 363 371-374 and I still get this.
macOS installer downloaded 3 times - checksum is not valid
@kc9wwh

**Comment by MusicMaker81** [comment]
> You can fix this by changing
> `if [ -n "$installESDChecksum" ]; then `
> to
> `if [ "$installESDChecksum" != "0" ]; then `
> and replace the empty value with 0 or to an actual hash if you want to use the feature.

This worked for me. 
The only thing is that de policy still downloads the macOS installer twice. I don't know why, but the pop-up with 'downloading' appears twice. When looking at the Activity Monitor you can also see that it is going to download a second time.
