### ISSUE TITLE
Feature request: make OS version agnostic

### ISSUE THREAD

**Issue by magnusviri** [kc9wwh/macOSUpgrade#15]
Would be nice if all of the "sierra" references were put in variables so this script could easily be used for other OS versions.

**Comment by patgmac** [comment]
https://github.com/kc9wwh/macOSUpgrade/pull/18/files starts to work towards that. There's still some verbiage in $description that would need to be updated. But we also don't know what 10.13 is going to look like just yet.

**Comment by patgmac** [comment]
Sorry, I did this before realizing you had a PR for this as well. I was mainly working towards using the existing cached Install macOS Sierra.app if it was current.
