### ISSUE TITLE
prepare-jamf-policy.sh with macOS Big Sur results in Unknown installer type.

### ISSUE THREAD

**Issue by dan-snelson** [kc9wwh/macOSUpgrade#150]
Using prepare-jamf-policy.sh with macOS Big Sur results in Unknown installer type:

`./prepare-jamf-policy.sh /Applications/Install\ macOS\ Big\ Sur.app`

Not found /Applications/Install macOS Big Sur.app/Contents/SharedSupport/InstallInfo.plist
Unknown installer type. Apple may change something.

**Comment by dan-snelson** [comment]
As a quick-and-dirty Big Sur Band-Aid, I locally made the following replacements:

- `/Contents/SharedSupport/InstallInfo.plist` with `/Contents/Info.plist`
- `/Contents/SharedSupport/InstallESD.dmg` with `/Contents/SharedSupport/SharedSupport.dmg`
- `"print 'System Image Info:version'" "${OSInstaller}/Contents/SharedSupport/InstallInfo.plist"` with `"print 'DTPlatformVersion'" "${OSInstaller}/Contents/Info.plist"`

**Comment by taniguti** [comment]
I fixed this issue #153.
Thank you.
