### ISSUE TITLE
macOS Big Sur: EraseInstall Not Completing

### ISSUE THREAD

**Issue by hankscafe** [kc9wwh/macOSUpgrade#155]
I am finding that I am unable to use the script to wipe and reinstall if Big Sur is macOS that is already on the computer.  It seems to hang after the "Please wait as we prepare..." window opens up, and then will reboot but it doesn't perform an --eraseinstall and instead just reinstalls the macOS.

Looking at the policy log in Jamf if see the below:

```
Installer found, version matches. Verifying checksum...
Usage:
/usr/bin/xpath5.28 [options] -e query [-e query...] [filename...]

If no filenames are given, supply XML on STDIN. You must provide at
least one query. Each supplementary query is done in order, the
previous query giving the context of the next one.

Options:

-q quiet, only output the resulting PATH.
-s suffix, use suffix instead of linefeed.
-p postfix, use prefix instead of nothing.
-n Don't use an external DTD.
(23) Failed writing body
Launching jamfHelper as Utility Window...
```

**Comment by bh5354** [comment]
My error is similar.
My test Macbook is already on macOS Big Sur 11.0.1
I am trying the erase then reinstall macOS Big Sur.

The command line I am executing is
sudo "/Applications/Install macOS Big Sur.app/Contents/Resources/startosinstall" --agreetolicense --nointeraction --forcequitapps --eraseinstall --newvolumename 'Macintosh HD'

When it does execute, I get a pop-up window asking for Admin rights.
"osisntallersetupd wants to make changes. Enter an administrator's name and password to allow this."

Researching this, it could be related to the fact that the Macbook has Filevault activated
https://github.com/kc9wwh/macOSUpgrade/issues/74
