### ISSUE TITLE
Script failed 

### ISSUE THREAD

**Issue by kotoky** [kc9wwh/macOSUpgrade#159]
When running the JAMF policy script, delete the current macOS Catalina installer from the Applications folder and try to download again. After 2-3 min show up again the OS  installer in the Application folder and take off the installer, and start over again to download it failed.

**Comment by kc9wwh** [comment]
Hey @kotoky, sorry to hear you’re having issues. 
- Can you confirm if you are using the latest version that was published last night?
- Can you provide a copy of the policy log?

**Comment by kotoky** [comment]
Yes I'm using the latest version 

Script result: installerVersion 10.15.0
installerVersion_Full_Integer 101500
installerVersion_Major_Integer 1015
Killing caffeinate processes.
No matching processes were found
Killing startosinstall processes.
No matching processes were found
Killing osinstallersetupd processes.
No matching processes were found
Power Check: OK - AC Power Detected
Disk Check: OK - 457017817096 Bytes Free Space Detected
Installer check: Expected: 10.15.0 Actual: 10.15.7
Try to download installer.app. (1 / 3 )
Downloading macOS Installer...
Checking for policies triggered by "download-catalina-install" for user "xxxxxxxx"...
Executing Policy Download macOS Catalaina
Downloading Install macOS Catalina.pkg...
Downloading https://use1-jcds.services.jamfcloud.com//download/600aecdaa9384057b3b02e2711dbd31e/Install%20macOS%20Catalina.pkg?token=8ba028a4a9f046d8be299c86af4db49bwpuqoqpt5qk02ha0kdqweavoevvmgtid...
Verifying package integrity...
Installing Install macOS Catalina.pkg...
Successfully installed Install macOS Catalina.pkg.
Submitting log to https://eze.jamfcloud.com/
Installer check: Expected: 10.15.0 Actual: 10.15.7
Try to download installer.app. (2 / 3 )
Downloading macOS Installer...
Checking for policies triggered by "download-catalina-install" for user "xxxxxxxx"...
Executing Policy Download macOS Catalaina
Downloading Install macOS Catalina.pkg...
Downloading https://use1-jcds.services.jamfcloud.com//download/600aecdaa9384057b3b02e2711dbd31e/Install%20macOS%20Catalina.pkg?token=8ba028a4a9f046d8be299c86af4db49bwpuqoqpt5qk02ha0kdqweavoevvmgtid...
Verifying package integrity...
Installing Install macOS Catalina.pkg...
Successfully installed Install macOS Catalina.pkg.
Submitting log to https://eze.jamfcloud.com/
Executing Policy Upgrade to macOS Catalina
Running script macOSUpgrade.sh...
Script exit code: 1
Script result: installerVersion 10.15.0
installerVersion_Full_Integer 101500
installerVersion_Major_Integer 1015
Killing caffeinate processes.
Killing startosinstall processes.
No matching processes were found
Killing osinstallersetupd processes.
No matching processes were found
Power Check: OK - AC Power Detected
Disk Check: OK - 457030611720 Bytes Free Space Detected
Installer check: Expected: 10.15.0 Actual: 10.15.7
Try to download installer.app. (1 / 3 )
Downloading macOS Installer...
This policy trigger is already being run: root              9086   0.0  0.2  4398368  27952   ??  S     5:15PM   2:20.95 /usr/local/jamf/bin/jamf policy -event download-catalina-install
Abort due to failed jamf policy -event download-catalina-install

Error running script: return code was 1.
Submitting log to https://eze.jamfcloud.com/
/Library/Application Support/JAMF/tmp/macOSUpgrade.sh: line 256:  8944 Terminated: 15          /usr/bin/caffeinate -dis
Abort due to failed jamf policy -event download-catalina-install

**Comment by kc9wwh** [comment]
@kotoky, per your policy log...
```
Installer check: Expected: 10.15.0 Actual: 10.15.7
```
You'll want to update **Script Parameter 5** in Jamf Pro to reflect what you are trying to install. In this case, `10.15.7`. Once you do that, you should be good to go.

**Comment by kotoky** [comment]
Hello,
that is a result of changing the version to 10.15.7

Script result: installerVersion 10.15.7
installerVersion_Full_Integer 101507
installerVersion_Major_Integer 1015
Killing caffeinate processes.
No matching processes were found
Killing startosinstall processes.
No matching processes were found
Killing osinstallersetupd processes.
No matching processes were found
Power Check: OK - AC Power Detected
Disk Check: OK - 464932532224 Bytes Free Space Detected
Installer check: Not found installer.app.
Try to download installer.app. (1 / 3 )
Downloading macOS Installer...
Checking for policies triggered by "download-catalina-install" for user "xxxxxxx"...
Executing Policy Download macOS Catalaina
Downloading Install macOS Catalina.pkg...
Downloading https://use1-jcds.services.jamfcloud.com//download/600aecdaa9384057b3b02e2711dbd31e/Install%20macOS%20Catalina.pkg?token=5f5a31719fc2468a82b79e9564bb28a9sckh3q0phmmz1u1s8fdqoy1xx6s3c7p0...
Verifying package integrity...
Installing Install macOS Catalina.pkg...
Successfully installed Install macOS Catalina.pkg.
Submitting log to https://eze.jamfcloud.com/
Installer check: Target version is ok (10.15.7).
Installer check: DMG file check: Skipped.
Installer check: PASSED
Launching jamfHelper as FullScreen.
Running a command as '"/Applications/Install macOS Catalina.app/Contents/Resources/startosinstall" --agreetolicense --nointeraction --pidtosignal 7767 --forcequitapps >> /var/log/startosinstall.log 2>&1 &'...

and failed to start the installer, the Install pkg is is on the Application folder

**Comment by kotoky** [comment]
Thanks a lot. It is working now. Just re-build the script policy. 
I really appreciate your help.

**Comment by kc9wwh** [comment]
Glad it's working for you now! Have a great day :)
