### ISSUE TITLE
prepare script failing for Big Sur

### ISSUE THREAD

**Issue by staze** [kc9wwh/macOSUpgrade#160]
Just grabbed latest prepare-jamf-policy.sh and pointing it at Big Sur, it goes to make the DMG, and then after a few minutes I see:

`Ok, building DMG file of Install macOS Big Sur.app. Wait few minutes.
cp: /Volumes/macOSInstaller/Applications/Install macOS Big Sur.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IABridgeOSInstall.framework/Versions/A/_CodeSignature/CodeResources: No space left on device
cp: /Volumes/macOSInstaller/Applications/Install macOS Big Sur.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IABridgeOSInstall.framework/Versions/A/Resources/framework.sb: No space left on device
cp: /Volumes/macOSInstaller/Applications/Install macOS Big Sur.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IABridgeOSInstall.framework/Versions/A/Resources/Info.plist: No space left on device
cp: /Volumes/macOSInstaller/Applications/Install macOS Big Sur.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IABridgeOSInstall.framework/Versions/A/Resources/version.plist: No space left on device
cp: /Volumes/macOSInstaller/Applications/Install macOS Big Sur.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IABridgeOSInstall.framework/Versions/A/Resources/BOSError.strings: No space left on device
cp: /Volumes/macOSInstaller/Applications/Install macOS Big Sur.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IAMiniSoftwareUpdate.framework/Versions/A/_CodeSignature/CodeResources: No space left on device
cp: /Volumes/macOSInstaller/Applications/Install macOS Big Sur.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IAMiniSoftwareUpdate.framework/Versions/A/Resources/Info.plist: No space left on device
cp: /Volumes/macOSInstaller/Applications/Install macOS Big Sur.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IAMiniSoftwareUpdate.framework/Versions/A/Resources/version.plist: No space left on device
cp: /Volumes/macOSInstaller/Applications/Install macOS Big Sur.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IAPackageKit.framework/Versions/A/_CodeSignature/CodeResources: No space left on device
cp: /Volumes/macOSInstaller/Applications/Install macOS Big Sur.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IAPackageKit.framework/Versions/A/Resources/Info.plist: No space left on device
cp: /Volumes/macOSInstaller/Applications/Install macOS Big Sur.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IAPackageKit.framework/Versions/A/Resources/version.plist: No space left on device
cp: /Volumes/macOSInstaller/Applications/Install macOS Big Sur.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IAInstallerUtilities.framework/Versions/A/_CodeSignature/CodeResources: No space left on device
cp: /Volumes/macOSInstaller/Applications/Install macOS Big Sur.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IAInstallerUtilities.framework/Versions/A/Resources/Info.plist: No space left on device
cp: /Volumes/macOSInstaller/Applications/Install macOS Big Sur.app/Contents/Frameworks/OSInstallerSetup.framework/Versions/A/Frameworks/IAESD.framework/Versions/A/Frameworks/IAInstallerUtilities.framework/Versions/A/Resources/version.plist: No space left on device
cp: /Volumes/macOSInstaller/Applications/Install macOS Big Sur.app/Contents/Info.plist: No space left on device
cp: /Volumes/macOSInstaller/Applications/Install macOS Big Sur.app/Contents/PkgInfo: No space left on device
cp: /Volumes/macOSInstaller/Applications/Install macOS Big Sur.app/Contents/version.plist: No space left on device
nx_kernel_mount:1473: : checkpoint search: largest xid 1652, best xid 1652 @ 27
nx_kernel_mount:1473: : checkpoint search: largest xid 1652, best xid 1652 @ 27
nx_kernel_mount:1473: : checkpoint search: largest xid 1652, best xid 1652 @ 27
nx_kernel_mount:1473: : checkpoint search: largest xid 1652, best xid 1652 @ 27
nx_kernel_mount:1473: : checkpoint search: largest xid 1652, best xid 1652 @ 27
nx_kernel_mount:1473: : checkpoint search: largest xid 1652, best xid 1652 @ 27
nx_kernel_mount:1473: : checkpoint search: largest xid 1652, best xid 1652 @ 27
nx_kernel_mount:1473: : checkpoint search: largest xid 1652, best xid 1652 @ 27
nx_kernel_mount:1473: : checkpoint search: largest xid 1652, best xid 1652 @ 27`

Drive isn't full on the machine, has 257GB available. It's like it's making the DMG too small.

**Comment by staze** [comment]
Looks like this might be an issue with running the script on a 10.14 machine... but not 100%. Will give a shot at running on 10.15 shortly.

**Comment by staze** [comment]
Nope. Fails in 10.15 as well. Looks like it's just making the DMG a little too small...

**Comment by taniguti** [comment]
Soory for inconvenience.
Let me check this issue.

**Comment by staze** [comment]
Thanks! and no inconvenience at all! Glad I could point out the issue, and looks like you've addressed. Going to give new version a go.
