### ISSUE TITLE
Installer Check Error with newest Big Sur Version

### ISSUE THREAD

**Issue by mikegshep** [kc9wwh/macOSUpgrade#162]
Parameter $5 "Version of macOS" expects a x.x.x format in order to distinguish the correct "Shared Support" path based on OS. If 11.1.0 is used, father down the script it will expect 11.1 when running an Installer check when comparing the DTPlatformVersion variable from the plist file contained in the Big Sur installer.

**Comment by timelost11** [comment]
Discovered this today as well. 

The checks for "$installerVersion_Full_Integer -lt 110000" are having trouble with 11.1, as it returns 1100 for the Full_Integer value. Lines 96 and 414.

I was able to work around this by adding a check on the length of $installerVersion_Full_Integer and adding "00" when the length is less than 6.

`/bin/echo "installerVersion $installerVersion"
/bin/echo "installerVersion_Full_Integer $installerVersion_Full_Integer"
/bin/echo "installerVersion_Major_Integer $installerVersion_Major_Integer"

######################################
if [[ "${#installerVersion_Full_Integer}" -lt 6 ]]; then
	/bin/echo "installerVersion_Full_Integer $installerVersion_Full_Integer"
	installerVersion_Full_Integer+="00"
	/bin/echo "installerVersion_Full_Integer set to $installerVersion_Full_Integer"
fi
######################################

if [ "$installerVersion_Full_Integer" -lt 110000 ]; then
    installerDMG="${OSInstaller}/Contents/SharedSupport/InstallESD.dmg"
    installerPlist="${OSInstaller}/Contents/SharedSupport/InstallInfo.plist"
else
    installerDMG="${OSInstaller}/Contents/SharedSupport/SharedSupport.dmg"
    installerPlist="${OSInstaller}/Contents/Info.plist"
fi`

**Comment by ripcon** [comment]
i dont know it it is just me but i have been trying to get the macOSUpgrade.sh to run but i can not get it past the check for the version number. I have used the helper script to generate the expected version number entered that into jamf and it still sees it as a mismatch. can not get the script to go past the check version with big sur 11.1

**Comment by kc9wwh** [comment]
Thanks for bringing this up. I actually ran into this today as well and will be working on getting a fix out ASAP.
