### ISSUE TITLE
macOS Big Sur 11.1 Fails to Upload - JAMF Support Says Use VPP Instead

### ISSUE THREAD

**Issue by rjtort** [kc9wwh/macOSUpgrade#164]
Been having issues uploading a .DMG of the macOS Big Sur 11.1 app to JAMF Cloud Distro. I've tried about 6 times now using the current version of JAMF Admin, the web browser (making sure to keep the session active while uploading), renaming the file, repackaging the file, and trying from multiple computers.After it uploads, when I look in JAMF Pro, it just says "Upload failed", but in JAMF Admin/the web upload, it shows that it completed fine. I've had issues previously with large files and the fix was to not have any spaces in the file name, so I've tried uploading this file as "macOS_Big_Sur.dmg" and "install_macOS_Big_Sur.dmg". No luck. 

Just got off the phone with JAMF Support about this and they say multiple tickets are popping up with this same issue. They escalated and said they'd get back to me, but suggested utilizing VPP to download the Install macOS Big Sur app instead. A great idea, as it removes the headache of having to package, upload 12.33 GB of data, and repeat any time there's a new update. The problem is the only options are to have it available in Self Service, or push automatically. It does work if you download from self service, then run the macOSUpgrade script, as it just sees the download already having completed. 

I was wondering if there's any way to trigger this download via the script, or scope things to a smart group to have it download when run. If possible, I can see this saving a lot of time and effort in the process.

**Comment by alfredhart** [comment]
This has been useful for creating the Big Sur PKG: https://gist.github.com/talkingmoose/e9ed319226c6da30dd633725e48a97b0

**Comment by wantedwriter** [comment]
Yes, I would recommend using the script above to build a .pkg rather than a .DMG.  Also upload via the Jamf webapp rather than Jamf Admin.  It is more reliable, especially with larger packages.

**Comment by dstocking** [comment]
Used the Gist for Big Sur and it worked like a charm!

**Comment by rjtort** [comment]
For me, it's still uploading using the package created with MegaPKGr, but if we could cut that whole process of needing to download the new version, package it, and upload it to JAMF, it would save a ton of time. 

Is there some way to trigger an app download via VPP/managed applications for the Big Sur download when running the macOSUpgrade.sh script, or in tandem with a command from JAMF?

**Comment by wantedwriter** [comment]
You could potentially use softwareupdate --fetch-full-installer command in place of a jamf policy but i doubt it would be as reliable.  I don't believe there is any way way to trigger a VPP download via command line.

**Comment by rjtort** [comment]
> You could potentially use softwareupdate --fetch-full-installer command in place of a jamf policy but i doubt it would be as reliable. I don't believe there is any way way to trigger a VPP download via command line.

I'll give that a shot. Thanks for the suggestion. 

Also, @alfredhart's suggestion for https://gist.github.com/talkingmoose/e9ed319226c6da30dd633725e48a97b0 uploaded successfully. That's the solution we'll be going with for now. Thanks all!
