### ISSUE TITLE
Big Sur Compatibility Checker

### ISSUE THREAD

**Issue by Blaban278** [kc9wwh/macOSUpgrade#176]
Hi @kc9wwh,
Thank you for sharing, 
That's what I've been looking for. 
I wold like to add to the Jamf Helper window some checks to ensure the Macs are plugged into power and have enough free space for the upgrade, Can you please help me understand how I do it most smoothly way?
Thanks

**Comment by dannyhanes** [comment]
@Blaban278 If you take a look at the script, those checks are already included.
