### ISSUE TITLE
Jamf article that refers to this Git is out of date.

### ISSUE THREAD

**Issue by franton** [kc9wwh/macOSUpgrade#19]
Hi,

Been working on my own variant of this. The article I followed first at https://www.jamf.com/blog/streamlining-your-macos-upgrade-process/ gave good hints but uses a --volumes / option that has been removed from the code on the GitHub.

Now I've independently made this discovery myself, just wondered if the page above could be updated as it was a little confusing!

**Comment by kc9wwh** [comment]
I've reached out to our communications folks and am working on getting either the blog updated or some kind of banner at the top of the page.

**Comment by kc9wwh** [comment]
We've added a notice at the top of the blog post:
_As of macOS 10.12.4 and later, this workflow has changed slightly. Please visit the GitHub repo for an updated version of this workflow._

I will also be writing an updated blog post when I get some time to discuss some of the changes and issues currently going on with deploying macOS Sierra.

**Comment by franton** [comment]
Excellent news!
