### ISSUE TITLE
10.12.6 support

### ISSUE THREAD

**Issue by ryanflanders** [kc9wwh/macOSUpgrade#25]
Thanks for creating this useful script. 

Any plans to update it to support the 10.12.6 installer?

**Comment by Whitebeer1337** [comment]
the latest release worked out great for me with 10.12.6 :)

**Comment by kc9wwh** [comment]
@ryanflanders Can you be more specific about what is not working, the syntax for the `startosinstall` binary doesn't appear to have changed for 10.12.6?

**Comment by ryanflanders** [comment]
I should have mentioned I modified the script for our environment. I found the issue was in my modifications, and it's working correctly now. 

Thanks again for your contribution!
