### ISSUE TITLE
Authenticated login is broken - 10.11.6 to 10.12.6

### ISSUE THREAD

**Issue by bwiessner** [kc9wwh/macOSUpgrade#27]
Upgraded two systems with this method - both made me login to unlock disk and then booted to installer. Authenticated restart did not happen. 

Both systems on 10.11.6 - using 10.12.6 installer.

**Comment by patgmac** [comment]
Known issue. See https://github.com/kc9wwh/macOSUpgrade/issues/13

Please report impact to Apple.
