### ISSUE TITLE
Question about icon usage when downloading installer

### ISSUE THREAD

**Issue by dammitbenny** [kc9wwh/macOSUpgrade#28]
When the installer is downloading and a message is presented to the user informing them of the download, what icon is presented?  The $icon variable appears to reference a file within the missing installer that is to be downloaded.

**Comment by patgmac** [comment]
Yes, that is a bug. Got any suggestions for what can be used if the installer is not present?

**Comment by dammitbenny** [comment]
I picked a download icon from a source that already existed in macOS.  The closest I could find was in the CoreTypes.bundle.  It's kind of grey and meh but it does the job.
"/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarDownloadFolder.icns"

**Comment by kc9wwh** [comment]
Thanks for the catch! Will be updating shortly!

**Comment by kc9wwh** [comment]
Added in v2.2
