### ISSUE TITLE
Variables

### ISSUE THREAD

**Issue by mpermann** [kc9wwh/macOSUpgrade#31]
With the impending release of macOS High Sierra, you might consider using a variable ($7) for the name of the OS. Then that variable can be used in the title (line 62) and heading (line 65) and line 86, 148 and 231. It would make the script a little more future proof and save editing the script for a newer OS.

**Comment by patgmac** [comment]
I added this with https://github.com/kc9wwh/macOSUpgrade/pull/34

**Comment by kc9wwh** [comment]
PR #34 has been merged. 
Resolved in v2.3.
