### ISSUE TITLE
Caffeinate

### ISSUE THREAD

**Issue by mpermann** [kc9wwh/macOSUpgrade#32]
Should caffeinate be invoked if the OS installer needs cached onto the system or will the `/usr/local/jamf/bin/jamf policy -event $download_trigger` keep the system awake?

**Comment by kc9wwh** [comment]
@mpermann The main reason it was added was to prevent the display from sleeping per Issue #20. As far as the `jamf` binary...I'm honestly not sure. I don't believe the computer would go to sleep, but I'm pretty sure we don't keep the display awake.
