### ISSUE TITLE
Tested with High Sierra?

### ISSUE THREAD

**Issue by jmartinFT** [kc9wwh/macOSUpgrade#35]
I suppose this is less of an "issue," and more so a question. I've tried to play around with this for High Sierra, and it doesn't seem to work. Anyone else been able to test this with HS and it execute properly?

**Comment by kc9wwh** [comment]
@jmartinFT Can you provide more info on what issues you are seeing? This has been tested with the macOS High Sierra betas without issue. I've been out of the office for the past couple weeks but will try to test again with the GM later this week.

**Comment by jmartinFT** [comment]
No worries, thanks for the response. 

With the script as is, it's not pulling the .icns file for the splash screen, and the install actually never starts. It'll download the pkg, execute the script for splash screen, but the install never actually executes.

I've used this with Sierra - and have had no problems. Just to test it, I let it sit for over 24 hours and it never actually installed.

**Comment by kc9wwh** [comment]
@jmartinFT It sounds like the installer is not actually getting laid down on the system or possibly not in the correct spot? If so, I'd check permissions. If the icns file is not being found though it leaves me to believe the installer isn't where it should be...

**Comment by jmartinFT** [comment]
That's what I was thinking too. However, all that seemed like it was correct. Currently working in a remote office. Will try again later this week. Thanks for the reply!

**Comment by jmartinFT** [comment]
I was finally able to run the script locally on a device successfully. Haven't tested again in our JSS. I'll mark this as closed. 

Thanks for your  responses.
