### ISSUE TITLE
Question: Minimum OS Requirement? 

### ISSUE THREAD

**Issue by dannyhanes** [kc9wwh/macOSUpgrade#38]
Is there a minimum OS requirement to run this script? If I have a client on 10.7, will this work?

**Comment by kc9wwh** [comment]
Hi @dannyhanes - The script as is, only supports the 10.12 installer or later. As far as the client side macOS version, as long as the device meets the minimum requirements of the macOS Installer you should be good to go. 

Always be sure to test first of course, but if you run into any issues please let me know.

**Comment by kc9wwh** [comment]
I added supported client macOS and Installer versions to the readme and script comments in the last release (v2.5)
