### ISSUE TITLE
Possible fix for authenticated reboot

### ISSUE THREAD

**Issue by smashism** [kc9wwh/macOSUpgrade#39]
Howdy! We've had a case open with Apple for while on the authenticate reboot issue, and got this reply:

> Engineering suspects this behavior may be the result of running the startosinstall command as root (or with sudo) rather than the currently logged in admin user.

The authenticated reboot issue might be resolved with a `sudo -u $user` if the script can grab the current console user. Haven't had a chance to test this myself yet but I've passed this along to someone else on the MacAdmins Slack who confirmed that calling startosinstall as the current user (needs to be admin, at least temporarily) gets the authenticated reboot to work as expected.

Thought I'd pass that along so someone can help validate.

**Comment by kc9wwh** [comment]
Hi @smashism, yes I've tested this, however when using this method the end-user gets prompted for elevated permissions to install a helper during this process which really isn't great since not all users have admin permissions and plus it pops up behind the jamfHelper window and just sits there :(

**Comment by kc9wwh** [comment]
Resolved in v2.5
