### ISSUE TITLE
Download Blocked until OK Clicked

### ISSUE THREAD

**Issue by mpermann** [kc9wwh/macOSUpgrade#43]
https://github.com/kc9wwh/macOSUpgrade/blob/34ec0f3c65831adf1cf28eb3d2557a9c19b5d70c/macOSUpgrade.sh#L155-L157
I'm wondering if some modifications could be made to this block of code to allow the `jamf policy -event $download_trigger` to execute even if a user doesn't click the OK button? In my testing, it seems that until you click the OK button it will not proceed with the download. I can see some of my users not clicking that OK button and wonder why it's just sitting there.

**Comment by mpermann** [comment]
Sounds good. For now I'll just add an `&` at the end of the command to get it to proceed and look forward to seeing what enhancements you make.

**Comment by MauricioPellizzon** [comment]
@kc9wwh I know this is to do with jamfHelper.app but is there a way to show that it is downloading in the FullScreen Dialog? Any user feedback showing that something is happening can/may prevent the user from rebooting.

**Comment by MauricioPellizzon** [comment]
Understood, we have changed the icon to something local to address that variable.
icon="/System/Library/CoreServices/Software Update.app/Contents/Resources/SoftwareUpdate.icns"

**Comment by kc9wwh** [comment]
@MauricioPellizzon - We'll see if the changes I just made work for folks, but otherwise we can always look at that in the future. 

Here is what the "new" HUD will look like...
![screenshot 2018-04-27 10 03 06](https://user-images.githubusercontent.com/9583412/39369627-67168058-4a02-11e8-94c3-8147533e938d.png)
