### ISSUE TITLE
Free space check changes again in 10.13.4

### ISSUE THREAD

**Issue by njellis** [kc9wwh/macOSUpgrade#47]
First off, great work on this!  It's much appreciated.

In my testing of your script, I've found that they have changed diskutil in 10.13.4 (currently beta) back to show "Free Space" instead of "Available Space" like in 10.12.0 - 10.13.3.  I think the following changes to your free space check should resolve this (and has so far in my experience).  This should give it a bit more future proofing, at least until they change it again...

```
##Check if free space > 15GB
osMinor=$( /usr/bin/sw_vers -productVersion )
if [[ $osMinor == 10.12.* ]] || [[ $osMinor > 10.12.* ]] && [[ $osMinor < 10.13.4 ]]; then
    freeSpace=$( /usr/sbin/diskutil info / | grep "Available Space" | awk '{print $6}' | cut -c 2- )
else
    freeSpace=$( /usr/sbin/diskutil info / | grep "Free Space" | awk '{print $6}' | cut -c 2- )
fi
```

Thanks!

**Comment by Morcin** [comment]
This will break a later part of the script that uses the osMinor variable:

`##Determine Program Argument
if [[ $osMinor -ge 11 ]]; then
    progArgument="osinstallersetupd"
elif [[ $osMinor -eq 10 ]]; then
    progArgument="osinstallersetupplaind"
fi`
