### ISSUE TITLE
Risk of running this while encrypting HD with FileVault

### ISSUE THREAD

**Issue by MauricioPellizzon** [kc9wwh/macOSUpgrade#49]
Not an issue with the solution itself but a point to be aware that we found out.
Trying to run the macOS upgrade while the FV is encrypting the drive caused major issues on our tests on VMs.
As a safeguard we added a criteria on our smart group to:
`FileVault 2 - Status  is not Encryption in progress`

**Comment by kc9wwh** [comment]
Thanks @MauricioPellizzon, I'll add this to the Readme.
