### ISSUE TITLE
Update Inventory

### ISSUE THREAD

**Issue by mpermann** [kc9wwh/macOSUpgrade#55]
The update inventory doesn't appear to be working for me in the workflow. Is anyone else having issues with the `jamf recon` not running for them?

**Comment by Hacksore** [comment]
In my experience with this it could be related to the system trying to fire the recon before it has network access. I've added a sleep of 30 seconds before the recon so that there is sufficient time for the device to connect.

Do you think that could be happening in your environment?

**Comment by kc9wwh** [comment]
If its network that is causing it, I can look at adding something like this into that script...

```
checkJSSConnection() {
    /usr/local/bin/jamf checkJSSConnection >> /dev/null
    while [ "$?" != "0" ]; do
        /bin/echo "Connection to Jamf Pro - Not Available"
        /bin/echo "    Waiting 30 seconds and trying again..."
        sleep 30
        /usr/local/bin/jamf checkJSSConnection >> /dev/null
    done
    /bin/echo "Connection to Jamf Pro - Successful"
}
```

Once available, I can then trigger the `jamf recon`.

**Comment by mpermann** [comment]
This sounds good. Thanks for your willingness to add this and I look forward to testing it.

**Comment by kenchan0130** [comment]
@kc9wwh 
Is this issue solved by this?

https://github.com/kc9wwh/macOSUpgrade/blob/1cfafc68a27b616cf6e5177249a77c59a95ad1cc/macOSUpgrade.sh#L286

**Comment by kenchan0130** [comment]
Close because it is probably resolved.
If you still have problems, please reopen.
