### ISSUE TITLE
Download Loops

### ISSUE THREAD

**Issue by swilliams83** [kc9wwh/macOSUpgrade#58]
Not sure what I am doing wrong, the download is looping/deleting itself and downloading again. Any help would be appreciated.

**Comment by mpermann** [comment]
Can you tell me the version of the Install macOS High Sierra installer that you are installing into /Applications? The correct version number of the installer is 13.5.04. If yours is older than that it would make sense that it's being deleted and re-downloaded if you are filling in the $5 variable with 10.13.5. Install the installer package you are using and check what the version number is. If it doesn't match the 13.5.04 then you will need to download a new full 10.13.5 installer from the Mac App store. Let me know if that doesn't resolve it.

**Comment by swilliams83** [comment]
@mpermann nope, still in the same boat.  I downloaded the installer again and the version is 13.5.04, also entering 10.13.5 in the $5 variable.

**Comment by mpermann** [comment]
How did you go about making the macOS High Sierra installer package that you are deploying for the upgrade? Did you use Composer or some other method? I used Composer and deploy the package to /Applications and I've not had any issues with the looping like you're describing @swilliams83. Maybe there is something wrong with the package that you're deploying where the version check is failing causing the package to get downloaded again.

**Comment by swilliams83** [comment]
ok, yeah there must be, I also used Composer, latest version downloaded today. It drops the "install macOS High Sierra.app" in /Applications. I'll keep digging.

**Comment by kc9wwh** [comment]
If you are not using the checksum feature, make sure there are not spaces or characters in there as well as that could trigger a re-download it is sees data in there.

You can also manually copy the installer over to a test machine and run just the script to see if it deletes it or not. This would tell you if the installer is actually coming down properly and be deleted or not. If so, you may also want to look at your `/var/log/jamf.log`

**Comment by swilliams83** [comment]
nope, no errors in jamf.log
getting:

Installing Install macOS High Sierra.pkg...
Successfully installed Install macOS High Sierra.pkg.
Submitting log to https://x.jamfcloud.com/
macOS Installer Downloaded 3 Times - Checksum is Not Valid
Prompting user for error and exiting...

**Comment by swilliams83** [comment]
my install macOS High Sierra.app doesn't have $OSInstaller/Contents/SharedSupport/InstallInfo.plist
looks like that is where the version info is checked, could this be my problem?

**Comment by kc9wwh** [comment]
@swilliams83 that could cause it as well, but from the logs you provided it is failing on the checksum verification. It looks like something is being passed in Parameter 7 of the script. Can you click into that filed and ensure that field is blank. If there is a space or anything that could be causing it.

**Comment by swilliams83** [comment]
Yes, $7 is empty. I also commented that whole section, lines 200-226, out with the exception of the downloadinstaller line. Still getting an error at helpertool crashing: 

/Library/LaunchAgents/com.apple.install.osinstallersetupd.plist: service already loaded
Launching startosinstall...
**Helper tool crashed...**
By using the agreetolicense option, you are agreeing that you have run this tool with the license only option and have read and agreed to the terms.
If you do not agree, press CTRL-C and cancel this process immediately.

Submitting log to https://kabbage.jamfcloud.com/

I guess it just hates me, lol

**Comment by mpermann** [comment]
@swilliams83 can you show a screen shot of your Composer window with the macOS High Sierra installer? For instance, here is what mine looks like.

<img width="1411" alt="screen shot 2018-07-02 at 4 52 18 pm" src="https://user-images.githubusercontent.com/7084083/42188255-c44223a0-7e18-11e8-91a8-fd8e279a2e37.png">

**Comment by swilliams83** [comment]
<img width="537" alt="screen shot 2018-07-02 at 6 32 16 pm" src="https://user-images.githubusercontent.com/40706051/42189457-52273d92-7e26-11e8-933b-321745b38a78.png">

yup, looks like I'm missing SharedSupport, downloaded the .app today, twice, rebuilt my policies from scratch and uploaded new .pkg and the script to my jss.

**Comment by mpermann** [comment]
@swilliams83 you may have the stub installer then. If the size of the installer isn't 5.23 GB then you don't have the full installer. You'll need the full installer for this deployment.

**Comment by mpermann** [comment]
We don't have a Jamf Cloud Distribution Point. I created a Cloud Distribution Point in Amazon's S3 that we use for systems off network. In order to get the installer loaded on that distribution point, I have to load it with CyberDuck as I've never been able to get very large packages like an OS installer to sync from our local AFP distribution point to the Cloud DP with Jamf Admin. I don't know if you can manually load the package with a Jamf Cloud or not.

**Comment by swilliams83** [comment]
So I guess I'll just put it in S3 and curl it down from there, this sucks. Also might be nice to indicate that the full installer is needed in the readme for the script. I may just be slow but feel like the full installer will resolve the issues I've been having and maybe save another slow person some time.

**Comment by swilliams83** [comment]
Nope, that is still looping also, just taking a very long time to loop with the larger download. Gonna look for alternatives, can't understand what I am possibly doing wrong.  The script is unaltered, variables all set, download triggered, either loops or helper tool crashing.
