### ISSUE TITLE
APFS vs HFS

### ISSUE THREAD

**Issue by albiii** [kc9wwh/macOSUpgrade#59]
I have a large mixture of SSD's, Spindle drives, and Fusion drives in my environment. Your script does work on all three without modification? I know the Erase flag only works on APFS.

**Comment by kc9wwh** [comment]
@albiii The script just helps facilitate the built in process of the installer. Over 99% of the script is just checking to ensure everything in is in place for the upgrade, its really just one line calling the installer and Apple's process takes it from there.

tldr: Yes, I don't any issues with having a mixture of drives in your environment.
