### ISSUE TITLE
Introduction of CI

### ISSUE THREAD

**Issue by kenchan0130** [kc9wwh/macOSUpgrade#66]
If you run [shellcheck](https://github.com/koalaman/shellcheck) on CI, I think that the script stability will increase.

**Comment by kenchan0130** [comment]
If you decide which CI you will use, I can contribute a configuration file.

**Comment by kc9wwh** [comment]
@kenchan0130 I've not set this up before, but will look into it.

**Comment by kc9wwh** [comment]
@kenchan0130 Do you have some recommendations to the `.travis.yml` file? [Here](https://github.com/kc9wwh/macOSUpgrade/blob/master/.travis.yml) is what I got so far. Just the starter file, but added `os: osx` per the Travis CI docs, but that appears to cause ShellChecker to not run. 

```
$ git clone --depth=50 --branch=master https://github.com/kc9wwh/macOSUpgrade.git kc9wwh/macOSUpgrade
Cloning into 'kc9wwh/macOSUpgrade'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 208 (delta 3), reused 5 (delta 2), pack-reused 199
Receiving objects: 100% (208/208), 1.43 MiB | 10.37 MiB/s, done.
Resolving deltas: 100% (113/113), done.
$ cd kc9wwh/macOSUpgrade
$ git checkout -qf c8c618e0ab69392729b1b6cbe6259309e579beb8
$ bash -c 'echo $BASH_VERSION'
3.2.57(1)-release
0.01s$ bash -c 'shopt -s globstar; shellcheck **/*.{sh,ksh,bash}'
bash: line 0: shopt: globstar: invalid shell option name
bash: shellcheck: command not found
The command "bash -c 'shopt -s globstar; shellcheck **/*.{sh,ksh,bash}'" exited with 127.
Done. Your build exited with 1.
```

I've removed `os: osx` for now.
