### ISSUE TITLE
Enrich readme

### ISSUE THREAD

**Issue by kenchan0130** [kc9wwh/macOSUpgrade#69]
It's just an idea, but I think that it is troublesome to use Composer app in "Staging the macOS Installer".

So, is it useful for users of this script to include in the readme that the following commands are acceptable?

```sh
pkgbuild --install-location /Applications --component "/path/to/macOSInstaller" "/path/to/xxxxx.pkg"
```

**Comment by kc9wwh** [comment]
@kenchan0130 I'm totally okay with adding this as another option on top of composer. Feel free to submit a PR.
