### ISSUE TITLE
Utility Window & Recon

### ISSUE THREAD

**Issue by mpermann** [kc9wwh/macOSUpgrade#7]
If you choose to set the UserDialog variable on line 58 to **1** it should execute the `if` statement on line 161 which means you might want the last word on line 162 changed to "Utility Window" to match with the type of window that gets used. 

I'm also wondering if maybe you want to add to the first boot script a `jamf recon` to perform a recon after the update is completed so the Casper server has an accurate representation of the installed OS.

By the way, this is a neat workflow that I'm going do some testing with to see if would work better than a createOSXpkg based workflow.

**Comment by kc9wwh** [comment]
hahahaha...gotta love the little things that get missed. I will get line 162 updated and add a jamf recon to the first boot script.

Let me know if everything works smoothly on createOSXPkg. It wasn't doing authenticated FileVault reboots when I tried and had some occasional issues with the upgrading requiring user input to proceed after the reboot.
