### ISSUE TITLE
Getting error when script is running

### ISSUE THREAD

**Issue by avivle** [kc9wwh/macOSUpgrade#75]
Hi,

I keep getting this error when script is running, what am I doing wrong?

<img width="797" alt="screen shot 2018-10-10 at 3 34 00 pm" src="https://user-images.githubusercontent.com/31063818/46736560-070f1f80-cca2-11e8-9a5c-b745e6ffd075.png">

The log from Jamf: 

<img width="494" alt="screen shot 2018-10-10 at 3 47 50 pm" src="https://user-images.githubusercontent.com/31063818/46737360-f790d600-cca3-11e8-91c1-b1f40439d014.png">
<img width="441" alt="screen shot 2018-10-10 at 3 48 08 pm" src="https://user-images.githubusercontent.com/31063818/46737370-fe1f4d80-cca3-11e8-9b88-8c9453cfdd84.png">
<img width="480" alt="screen shot 2018-10-10 at 3 48 17 pm" src="https://user-images.githubusercontent.com/31063818/46737383-037c9800-cca4-11e8-83ee-2f57e68f3a89.png">

Thanks...

**Comment by qu1gl3s** [comment]
It looks like you're making comments for the name that aren't needed with your example of /Applications/Install\ macOS\ Mojave.app

Removing those backslashes might give you the result you're looking for.

**Comment by kenchan0130** [comment]
It seems that this issue was solved.

If you still have problems, please reopen here or issue again.
