### ISSUE TITLE
jamfHelper error

### ISSUE THREAD

**Issue by qu1gl3s** [kc9wwh/macOSUpgrade#76]
Hi,

I've been trying to upgrade some of our clients from 10.11.6 to 10.13.6 and been seeing an issue with the part of the script that start the jamfHelper session to inform the user the installation is preparing.

The error I'm receiving is this:

`2018-10-12 16:06:33.306 jamfHelper[4196:181406] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data`

After some investigation, I found a Jamf Nation post mentioning this was an issue on 10.11 with jamfHelper.

https://www.jamf.com/jamf-nation/discussions/17457/jamfhelper-policy-error-failed-to-create-global-data

Any chance the workaround in that thread could be inputted to check if the machine is running 10.11 that it can run jamfHelper properly?

I'm looking at trying to add this functionality myself and if I'm happy with the results, I make a pull request of my changes for you to review.

Thanks!

**Comment by kenchan0130** [comment]
@kc9wwh 
I don't familiar with jamfhelper of 10.11. 

According to jamf-nation, we can execute the jamfhelper command as an executable user rather than the jamf agent user (root).
Do you know anything about this?

**Comment by kenchan0130** [comment]
This problem is the same as https://github.com/kc9wwh/macOSUpgrade/issues/24.
Therefore, I will close this issue. Let us do the rest there.
