### ISSUE TITLE
Launch Daemon and Script Removal

### ISSUE THREAD

**Issue by mpermann** [kc9wwh/macOSUpgrade#8]
In testing the work flow, I found that the launch daemon and script were not being deleted after the installation was completed. I found that if I deleted the launch daemon before unloading it that it would delete. If the launch daemon was unloaded first the rest of the script would not complete. Below are some modifications I did to get the launch daemon and script to delete at the end of the process. 

```
## Remove LaunchDaemon
/bin/rm -f /Library/LaunchDaemons/com.jamfps.cleanupOSInstall.plist

## Remove finishOSInstall.sh
/bin/rm -f /usr/local/jamfps/finishOSInstall.sh

## Unloading launch daemon
/bin/launchctl unload -w /Library/LaunchDaemons/com.jamfps.cleanupOSInstall.plist
```
I'm a scripting newbie, so I don't know whether what I'm suggesting is appropriate or not. I just know that in my limited testing it seemed to work ok.

**Comment by kc9wwh** [comment]
Thanks for the info @mpermann. I will have time next week to work on this and will add additional workflows to ensure this gets cleaned up properly.

**Comment by kc9wwh** [comment]
Fixed in v1.7

Thank you @mpermann!

**Comment by mpermann** [comment]
Was cleaning up the /usr/local/jamfps/ directory and the /usr/local/jamfps/finishOSInstall.sh file something you didn't want to add to the script or did you just forget those items? If it's not something you want in yours that's cool, I can add it to mine.

**Comment by kc9wwh** [comment]
Doh!

My bad, be uploaded shortly...
