### ISSUE TITLE
Compatible with macOS Mojave? 

### ISSUE THREAD

**Issue by AxeKR** [kc9wwh/macOSUpgrade#81]
trying the eraese & install with 10.14 and running into an error: erease & install requieres macOS 10.13.4+

Thank you for your great work. it helps me much to get my jamf enviroment up and running. i'm learning every day something new.

**Comment by kc9wwh** [comment]
@AxeKR my understanding is the client just needed to be APFS formatted and that the installer had to be 10.13.4 or later. I've tested from 10.13.5 to 10.14.0 and back to 10.13.5 without issue, but haven't tested on versions earlier to that.

Just to ensure we're on the same page, you have a system on macOS 10.13 (but prior to 10.13.4) and is APFS formatted and trying to do the `--eraseInstall`` option to upgrade macOS Mojave?

Let me know. :)

**Comment by AxeKR** [comment]
argh, no i was trying form 10.12.6. ough will give it a try. thank you

**Comment by kc9wwh** [comment]
No problem! But yes, the `--eraseInstall` options does requires an APFS formatted volume which requires macOS 10.13+.

**Comment by AxeKR** [comment]
---
