### ISSUE TITLE
Wrong upgrade occurred when 2 OS installers are present?

### ISSUE THREAD

**Issue by Genesis2kx** [kc9wwh/macOSUpgrade#88]
I have all the variables harcoded such as OS version, OS installer path etc using this script to use for mojave.

I am preloading the Installer app to /Applications before hand so no downloading is needed in the moment. I have both the high Sierra 10.13.5 and 10.14.1 installers present on the machines typically.
However,  on 2 out of 7 machines i've upgraded with this script ended up on high sierra 10.13.5 instead of mojave 10.14.1.

Is there some pattern matching logic in this script that could cause the wrong installer to start when both are present even though I have the variables hard-coded to mojave in the script?

I'm running via self-service in JAMF and the policy logs clearly show the mojave script being called.
I notice the startoinstall.log file doesn't exist post-installation, i'm guessing it's cleaned up at some point, so i'm not sure where else I can look for clues to deduce how this is possible.

**Comment by kenchan0130** [comment]
I think you can use this script in any directory other than `/Applications` if https://github.com/kc9wwh/macOSUpgrade/pull/85 will be merged.

**Comment by kc9wwh** [comment]
Being that the `OSInstaller` variable should be hardcoded in Parameter 4, I'm really not sure how this could happen. If you can duplicate this, changing line 1 to add the `-x` at the end, should help figure out where things are getting crossed.
```#!/bin/bash -x```

**Comment by kc9wwh** [comment]
I've merged PR #85, let me know if you are still having issues.

**Comment by kenchan0130** [comment]
It seems that this issue was solved.

If you still have problems, please reopen here or issue again.
