### ISSUE TITLE
macOS 10.12.4 Installer

### ISSUE THREAD

**Issue by mpermann** [kc9wwh/macOSUpgrade#9]
The new macOS 10.12.4 installer doesn't seem to work with this workflow. I'm not sure, but I think something has changed with the startosinstall binary. I'm not having any luck anyway getting it to work. If I figure anything out I'll post back.

**Comment by chasetb** [comment]
It appears that there is a new argument in the help documentation called `agreetolicense`. I wonder if this replaces `nointeraction`.

**Comment by kc9wwh** [comment]
Interesting...I know the `nointeraction`flag has been hidden from the documentation, I hope they didn't remove it...let me know. I won't be able to test this until next week.

**Comment by chasetb** [comment]
`nointeraction` is still listed in the `strings` output so I guess it's still an option. I haven't had time to fully test it yet.

**Comment by mpermann** [comment]
If I remove `--volume /` from 
`/Users/Shared/Install\ macOS\ Sierra.app/Contents/Resources/startosinstall --volume / --applicationpath /Users/Shared/Install\ macOS\ Sierra.app --nointeraction --pidtosignal $jamfHelperPID & `
the workflow begins working again. The only issue I've noticed is if the volume is encrypted with FileVault 2 it will stop at the FileVault screen until you enter in the password. With 10.12.3 this didn't happen. It would do an authenticated restart properly without any intervention needed from the end user. This is not the desirable behavior.

**Comment by chasetb** [comment]
I'm seeing the same as you, @mpermann. Using the `volume` argument just causes the help documentation to be printed. Removing it allows the command to run as expected. The argument `agreetolicense` appears to not affect `nointeraction` one way or the other as well.

**Comment by rqomsiya** [comment]
This worked for me:

`	##Begin Upgrade
	/bin/echo "Launching startosinstall..."
	/Users/Shared/Install\ macOS\ Sierra.app/Contents/Resources/startosinstall --applicationpath /Users/Shared/Install\ macOS\ Sierra.app --nointeraction --pidtosignal $jamfHelperPID &
    /bin/sleep 3
else`

**Comment by bdelamarche** [comment]
Hi,

It's working with the scripts thanks to Laurent Pertois for sharing an thanks to Joshua Roskos for this.
We just adapt a little bit the script for 10.12.4 because some option are no more present in the .app installer

Line 79 to 86

Check if installer is present

if [ -d /Users/Shared/Install\ macOS\ Sierra.app ]; then installerPresent="OK" /bin/echo "Installer present: OK - the installer is in /Users/Shared"
else installerPresent="ERROR" /bin/echo "Installer present: ERROR - the installer is not in /Users/Shared"
fi

Line 118
/bin/mkdir -p /usr/local/jamfps

Line 164
if [[ ${pwrStatus} == "OK" ]] && [[ ${spaceStatus} == "OK" ]] && [[ ${installerPresent} == "OK" ]]; then

Line 179 /Users/Shared/Install\ macOS\ Sierra.app/Contents/Resources/startosinstall --applicationpath /Users/Shared/Install\ macOS\ Sierra.app --agreetolicense --pidtosignal $jamfHelperPID &

On our side all is working with this workflow

**Comment by bdelamarche** [comment]
[[ALL]_installer_macos_sierra_10.12.4.sh.zip](https://github.com/kc9wwh/macOSUpgrade/files/883082/ALL._installer_macos_sierra_10.12.4.sh.zip)

**Comment by cpwasthere** [comment]
I can confirm that rqomsiya's change enables it to install and restart successfully with 10.12.4 but FV authenticated restart is not working and the password has to be entered upon reboot.  With 10.12.3, FV authenticated restart worked without issue.

**Comment by kc9wwh** [comment]
Thanks for the information @mpermann, @chasetb, @rqomsiya , @bdelamarche and @cpwasthere.

I have time set aside to work on this next week. I'm not sure at this time if these changes to the 10.12.4 installer are intentional or not, but we'll do our best to find a solution/workaround in the meantime to this situation. I have a couple ideas to try, just need time in the office to test them out.

**Comment by rqomsiya** [comment]
@cpwasthere I haven't seen that issue on my machines.

**Comment by kc9wwh** [comment]
@rqomsiya Are your systems FV encrypted? And you are saying that when they reboot to the installer volume this is happening automatically without having to enter FV credentials?

**Comment by rqomsiya** [comment]
They are FV2 encrypted. Upgrading from 10.11.5. I'm verifying with users if they had to enter creds

**Comment by ArcOne** [comment]
using @bdelamarche modified script everything is working for me except i the authenticated restart. going form 10.11.6 to 10.12.4

**Comment by cpwasthere** [comment]
@rqomsiya Yes we are FV2 encrypted as well.  Going from 10.11.6 to 10.12.3 worked fine, authenticated restart and all.  Doing the same to 10.12.4, no authenticated restart and user has to put their password in to complete the upgrade process.

**Comment by rqomsiya** [comment]
I have verified with my users that they are NOT getting promoted to authenticate FV after a restart to complete the installation. I wonder what my deltas are? Or your deltas?

**Comment by kc9wwh** [comment]
@rqomsiya Can you provide details of how your doing this workflow? I've ran through several tests today and have not been able to get the FileVault authenticated reboot to work except when the "Install macOS Sierra.app" is run via the GUI.

I'm in a process of opening a ticket with Apple, but very curious as to what you are seeing and how you are accomplishing this.

**Comment by mpermann** [comment]
@kc9wwh I'm seeing the same as you in my testing. No FileVault authenticated restart using the workflow you've developed. If I run the installer from the App store without any automation I do get a FileVault authenticated restart. Either Apple accidentally broke something or they did it on purpose. The latter wouldn't surprise me sadly. I'd be happy to dupe your radar report if you open one. I'm planning to use this workflow to deploy macOS Sierra to around 800 computers soon.

**Comment by rqomsiya** [comment]
hi @kc9wwh. I'm just calling the installer normally. Here is the script:

`#!/bin/bash

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# 
# This script was designed to be used in a Self Service policy to ensure specific
# requirements have been met before proceeding with an inplace upgrade to macOS Sierra, 
# as well as to address changes Apple has made to the ability to complete macOS upgrades 
# silently. 
# 
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# USER VARIABLES
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

##Enter 0 for Full Screen, 1 for Utility window (screenshots available on GitHub)
userDialog=0

##Title to be used for userDialog (only applies to Utility Window)
title="macOS Sierra Upgrade"

##Heading to be used for userDialog
heading="Please wait as we prepare your computer for macOS Sierra..."

##Title to be used for userDialog
description="
This process will take approximately 5-10 minutes. 
Once completed your computer will reboot and begin the upgrade."

##Icon to be used for userDialog
##Default is macOS Sierra Installer logo which is included in the staged installer package
icon=/Users/Shared/Install\ macOS\ Sierra.app/Contents/Resources/InstallAssistant.icns

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# SYSTEM CHECKS
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

##Check if device is on battery or ac power
pwrAdapter=$( /usr/bin/pmset -g ps )
if [[ ${pwrAdapter} == *"AC Power"* ]]; then
	pwrStatus="OK"
	/bin/echo "Power Check: OK - AC Power Detected"
else
	pwrStatus="ERROR"
	/bin/echo "Power Check: ERROR - No AC Power Detected"
fi

##Check if free space > 15GB
osMinor=$( /usr/bin/sw_vers -productVersion | awk -F. {'print $2'} )
if [[ $osMinor -ge 12 ]]; then
	freeSpace=$( /usr/sbin/diskutil info / | grep "Available Space" | awk '{print $4}' )
else
	freeSpace=$( /usr/sbin/diskutil info / | grep "Free Space" | awk '{print $4}' )
fi

if [[ ${freeSpace%.*} -ge 15 ]]; then
	spaceStatus="OK"
	/bin/echo "Disk Check: OK - ${freeSpace%.*}GB Free Space Detected"
else
	spaceStatus="ERROR"
	/bin/echo "Disk Check: ERROR - ${freeSpace%.*}GB Free Space Detected"
fi

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# CREATE FIRST BOOT SCRIPT
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

/bin/mkdir /usr/local/jamfps

/bin/echo "#!/bin/bash
## First Run Script to remove the installer.

## Clean up files
/bin/rm -fdr /Users/Shared/Install\ macOS\ Sierra.app
/bin/sleep 2
/usr/local/jamf/bin/jamf recon

## Remove LaunchDaemon
/bin/launchctl unload -w /Library/LaunchDaemons/com.jamfps.cleanupOSInstall.plist
/bin/rm -f /Library/LaunchDaemons/com.jamfps.cleanupOSInstall.plist

exit 0" > /usr/local/jamfps/finishOSInstall.sh

/usr/sbin/chown root:admin /usr/local/jamfps/finishOSInstall.sh
/bin/chmod 755 /usr/local/jamfps/finishOSInstall.sh

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# LAUNCH DAEMON
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

/bin/echo "<?xml version="1.0" encoding="UTF-8"?> 
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd"> 
<plist version="1.0"> 
<dict>
	<key>Label</key> 
	<string>com.jamfps.cleanupOSInstall</string> 
	<key>ProgramArguments</key> 
	<array> 
		<string>/usr/local/jamfps/finishOSInstall.sh</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict> 
</plist>" > /Library/LaunchDaemons/com.jamfps.cleanupOSInstall.plist

##Set the permission on the file just made.
/usr/sbin/chown root:wheel /Library/LaunchDaemons/com.jamfps.cleanupOSInstall.plist
/bin/chmod 644 /Library/LaunchDaemons/com.jamfps.cleanupOSInstall.plist

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 
# APPLICATION
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # 

if [[ ${pwrStatus} == "OK" ]] && [[ ${spaceStatus} == "OK" ]]; then
    ##Launch jamfHelper
    if [[ ${userDialog} == 0 ]]; then
    	/bin/echo "Launching jamfHelper as FullScreen..."
	    /Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType fs -title "" -icon "$icon" -heading "$heading" -description "$description" &
	    jamfHelperPID=$(echo $!)
    fi
    if [[ ${userDialog} == 1 ]]; then
	    /bin/echo "Launching jamfHelper as Utility Window..."
	    /Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType utility -title "$title" -icon "$icon" -heading "$heading" -description "$description" -iconSize 100 &
	    jamfHelperPID=$(echo $!)
    fi

	##Begin Upgrade
	/bin/echo "Launching startosinstall..."
	/Users/Shared/Install\ macOS\ Sierra.app/Contents/Resources/startosinstall --applicationpath /Users/Shared/Install\ macOS\ Sierra.app --nointeraction --pidtosignal $jamfHelperPID &
    /bin/sleep 3
else
	/bin/echo "Launching jamfHelper Dialog (Requirements Not Met)..."
	/Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType utility -title "$title" -icon "$icon" -heading "Requirements Not Met" -description "We were unable to prepare your computer for macOS Sierra. Please ensure you are connected to power and that you have at least 15GB of Free Space. 
	
	If you continue to experience this issue, please contact the TSD." -iconSize 100 -button1 "OK" -defaultButton 1
fi

exit 0`

**Comment by cpwasthere** [comment]
@rqomsiya Are you only using that line in your workflow or are you still using the entire script?

**Comment by rqomsiya** [comment]
@cpwasthere Im using the entire script.

**Comment by rqomsiya** [comment]
@kc9wwh @cpwasthere Do you have any other apps installing at first boot?

**Comment by cpwasthere** [comment]
@rqomsiya Nope, this just doing an upgrade from El Cap in self service.  Nothing else getting installed.

**Comment by TheDecline13** [comment]
I am seeing the same issue with FV authentication. It prompts after the reboot, once PW is entered it continues with the upgrading. BTW thats for the work, its very appreciated.

**Comment by kc9wwh** [comment]
Sorry for the delay folks...I filed this bug report yesterday. Waiting to hear back yet, but as for right now it looks like they've removed that functionality (intentionally or not).

rdar://31410389

**Comment by kc9wwh** [comment]
Opened new Issue #13 for FileVault Support.

Script has been updated for macOS Sierra Installer v12.4.06 in v1.7.

Thank you @mpermann, @chasetb, @rqomsiya, @bdelamarche, @cpwasthere and @TheDecline13

**Comment by TheDecline13** [comment]
Awesome! I am going to test this right now and report back
