### ISSUE TITLE
Caught in a loop while downloading-installing....

### ISSUE THREAD

**Issue by Chrisuhaeli** [kc9wwh/macOSUpgrade#93]
Hello all.

I played along with this macOSupgrade script pretty long (two days), but cannot get it to work properly, as it runs the download-mojave-install trigger three times and then quits with an error, and I don't get the idea why.

I left the script pretty much in default. Left the MD5 checksum parameter empty and the other script settings that might go into account for this issue by their defaults (verifyChecksum=0, unsuccessfulDownload=0):

**##MD5 Checksum of InstallESD.dmg
##This variable is OPTIONAL
##Leave the variable BLANK if you do NOT want to verify the checksum (DEFAULT)
##Example Command: /sbin/md5 /Applications/Install\ macOS\ High\ Sierra.app/Contents/SharedSupport/InstallESD.dmg
##Example MD5 Checksum: b15b9db3a90f9ae8a9df0f81741efa2b
installESDChecksum="$7"

##Valid Checksum?  O (Default) for false, 1 for true.
validChecksum=0

##Unsuccessful Download?  0 (Default) for false, 1 for true.
unsuccessfulDownload=0**

As recommended, I built a custom-triggered policy just for the installer pkg that I built in Jamf Composer. The macOsUpgrade script calls this, but for some odd reason for three times before it stops with an error.

Here ist what the Jamf log says:

**_Script_ result: Power Check: OK - AC Power Detected
Disk Check: OK - 462553731072 Bytes Free Space Detected
Downloading macOS Installer...
Checking for policies triggered by "download-mojave-install" for user "christian.bednarz"...
Executing Policy macOS Mojave 10.14.3
Mounting Germany DP
Installing Install macOS Mojave 10.14.3.pkg...
Successfully installed Install macOS Mojave 10.14.3.pkg.
Unmounting file server...
Submitting log to https://jss.ourserver.lan
Downloading macOS Installer...
/Library/Application Support/JAMF/tmp/macOSupgrade.sh: line 147:  1131 Terminated: 15          /Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType hud -windowPosition $dlPosition -title "$title" -alignHeading center -alignDescription left -description "$dldescription" -lockHUD -icon "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarDownloadsFolder.icns" -iconSize 100
Checking for policies triggered by "download-mojave-install" for user "christian.bednarz"...
Executing Policy macOS Mojave 10.14.3
Mounting Germany DP
Installing Install macOS Mojave 10.14.3.pkg...
Successfully installed Install macOS Mojave 10.14.3.pkg.
Unmounting file server...
Submitting log to https://jss.ourserver.lan/
Downloading macOS Installer...
/Library/Application Support/JAMF/tmp/macOSupgrade.sh: line 147:  1359 Terminated: 15          /Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType hud -windowPosition $dlPosition -title "$title" -alignHeading center -alignDescription left -description "$dldescription" -lockHUD -icon "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarDownloadsFolder.icns" -iconSize 100
Checking for policies triggered by "download-mojave-install" for user "christian.bednarz"...
Executing Policy macOS Mojave 10.14.3
Mounting Germany DP
Installing Install macOS Mojave 10.14.3.pkg...
Successfully installed Install macOS Mojave 10.14.3.pkg.
Unmounting file server...
Submitting log to https://jss.ourserver.lan/
macOS Installer Downloaded 3 Times - Checksum is Not Valid
/Library/Application Support/JAMF/tmp/macOSupgrade.sh: line 258:  1577 Terminated: 15          /Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType hud -windowPosition $dlPosition -title "$title" -alignHeading center -alignDescription left -description "$dldescription" -lockHUD -icon "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarDownloadsFolder.icns" -iconSize 100
Prompting user for error and exiting...
0_**

I find the message "checksum is not valid" irritating, as it should not check the checksum at all. Anyway, I did try with the checksum thingie before, but it also failed. I also tried reuploading the pkg installer to Jamf Admin again, but still issue remains.

Any thoughts on this? I feel somehow desperate and like being in a mental treadmill for hours now... Thank you...

**Comment by kc9wwh** [comment]
Hey @Chrisuhaeli, 

Sorry to hear you are having issues with the script and we'll get the log message updated because it can be one of two things that can cause the script to deny the installed package and that is a invalid checksum (if enabled) and the Installer macOS Version differing from what is specified. 

Couple questions...
- Could you please provide a screenshot of the script payload in your policy to see how the parameters are filled in? 
- Also, can you please upload a copy of `/path/to/Install macOS Mojave.app/Contents/SharedSupport/InstallInfo.plist` from the packaged pkg?

Thanks!

**Comment by kc9wwh** [comment]
Hey @Chrisuhaeli,

I'll look more closely at this after my call this morning, but try removing the `\` from within the `Installer Path`. This variable is quoted throughout the script so those are not needed. Also check just to ensure there isn't a space in the MD5 checksum parameter. But otherwise at first glance it does all look right.

**Comment by Chrisuhaeli** [comment]
Okay, perfect. I just try and check and give an update tomorrow. :-)

**Comment by kc9wwh** [comment]
Cool :)

Where do you see that example? The one for the parameter should be showing correct...
```
##Specify path to OS installer. Use Parameter 4 in the JSS, or specify here
##Example: /Applications/Install macOS High Sierra.app
OSInstaller="$4"
```

**Comment by devlinford** [comment]
I don't mean to hijack or interject here...but @kc9wwh, any chance I can get some support on an issue I'm seeing with this script?

I've dropped a couple issue requests in and haven't heard back from anyone and hoping you can take a look?

**Comment by Chrisuhaeli** [comment]
I confirm resolution. Thanks again for the swift response. :-)

**Comment by alexthefourth** [comment]
Hello, new here. i was looking at this to see if it can solve a problem Im having but I noticed that your parameter values have the parameter names but mine still say Parameter 4-11. What is responsible for changing the parameter names?

![screen shot 2019-01-28 at 2 36 14 pm](https://user-images.githubusercontent.com/4157807/51871097-43769200-230a-11e9-923f-27902bc9a80b.png)

After running the policy via self service this is the error I get in the logs

`Script result: Power Check: OK - AC Power Detected
Disk Check: OK - 241677692928 Bytes Free Space Detected
Downloading macOS Installer...
Checking for policies triggered by "download-mojave-install" for user "alex"...
Executing Policy TEST Cache Mojave
Downloading macOS_Mojave.pkg...
Downloading https://d2ru1bkaq3h63l.cloudfront.net/macOS_Mojave.pkg...
Installing macOS_Mojave.pkg...
Successfully installed macOS_Mojave.pkg.
Running Recon...
Retrieving inventory preferences from https://science37.jamfcloud.com/...
Finding extension attributes...
Locating applications...
Locating accounts...
Locating package receipts...
Searching path: /Applications
Locating hard drive information...
Locating software updates...
Locating plugins...
Locating printers...
Searching path: /Users/ryan/Library/Internet Plug-Ins
Searching path: /Users/alex/Library/Internet Plug-Ins
Searching path: /private/var/jss_admin/Library/Internet Plug-Ins
Searching path: /Library/Internet Plug-Ins
Searching path: /Users/tempadmin/Library/Internet Plug-Ins
Locating hardware information (Mac OS X 10.12.6)...
Gathering application usage information...
Searching path: /Users
Submitting data to https://science37.jamfcloud.com/...
<computer_id>66</computer_id>
Submitting log to https://science37.jamfcloud.com/
/Applications/Install_macOS_Mojave.app found, checking version.
/Library/Application Support/JAMF/tmp/TEST macOSUpgrade.sh: line 249: 59807 Terminated: 15          /Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType hud -windowPosition $dlPosition -title "$title" -alignHeading center -alignDescription left -description "$dldescription" -lockHUD -icon "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarDownloadsFolder.icns" -iconSize 100
OSVersion is 10.14.2
Installer found, but old. Deleting...
Downloading macOS Installer...
Checking for policies triggered by "download-mojave-install" for user "alex"...
No policies were found for the "download-mojave-install" trigger.
Downloading macOS Installer...
/Library/Application Support/JAMF/tmp/TEST macOSUpgrade.sh: line 142: 62798 Terminated: 15          /Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType hud -windowPosition $dlPosition -title "$title" -alignHeading center -alignDescription left -description "$dldescription" -lockHUD -icon "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarDownloadsFolder.icns" -iconSize 100
Checking for policies triggered by "download-mojave-install" for user "alex"...
No policies were found for the "download-mojave-install" trigger.
macOS Installer Downloaded 3 Times - Checksum is Not Valid
/Library/Application Support/JAMF/tmp/TEST macOSUpgrade.sh: line 256: 62917 Terminated: 15          /Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType hud -windowPosition $dlPosition -title "$title" -alignHeading center -alignDescription left -description "$dldescription" -lockHUD -icon "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarDownloadsFolder.icns" -iconSize 100
Prompting user for error and exiting...
0`

Is the error related to my parameters?

**Comment by MauricioPellizzon** [comment]
@alexthefourth Yes, the parameter is the cause of it. In the script...
```
##Version of Installer OS. Use Parameter 5 in the JSS, or specify here.
##Example Command: /usr/libexec/PlistBuddy -c 'Print :"System Image Info":version' "/Applications/Install macOS High Sierra.app/Contents/SharedSupport/InstallInfo.plist"
##Example: 10.12.5
```
Hope this helps.

**Comment by Chrisuhaeli** [comment]
@alexthefourth The parameter labels (not values) can be defined in the script section itself (Settings - Computer Management - Scripts - name_of_script.sh, in the Options tab. But this is really just cosmetic, if you leave the defaults, this will work, too, of course (given that you do not mix up ;-))

![screenshot 2019-01-29 at 11 11 22](https://user-images.githubusercontent.com/46998845/51900986-e1279b00-23b6-11e9-984a-a77a1231f889.png)
