### ISSUE TITLE
Installer found, but old. Deleting - again and again

### ISSUE THREAD

**Issue by AxeKR** [kc9wwh/macOSUpgrade#94]
Using the script for Upgrade and Clean install. Upgrade ist working fine until it is a 10.13.6 os with FV active and a standard user but thats on the other hand. My Problem is that the script is deleting the mac os installer because it is old? and the cat bits in the tail and the job is failing.

Whats going on? 

Locating hardware information (Mac OS X 10.14.1)...
Submitting data to https://jamf.
OSVersion is 10.14.1
Installer found, but old. Deleting...
Downloading macOS Installer...
Checking for policies triggered by "download-mojave-install" for user "akrause"...
Executing Policy OS: Move Install App into the right Place
Downloading Install macOS Mojave.pkg...
Downloading 
Installing Install macOS Mojave.pkg...
Successfully installed Install macOS Mojave.pkg.

OSVersion is 10.14.1
Installer found, but old. Deleting...
Downloading macOS Installer...

**Comment by kc9wwh** [comment]
@AxeKR please provide a screenshot of your script parameters within the policy. Based on just the log my assumption is the policy is configured to a different target version.

**Comment by AxeKR** [comment]
<img width="865" alt="bildschirmfoto 2019-02-06 um 16 52 23" src="https://user-images.githubusercontent.com/44817288/52353849-a3b6b380-2a2f-11e9-98fc-d1ea3b0256f8.png">

**Comment by AxeKR** [comment]
Script result: Power Check: ERROR - No AC Power Detected
Disk Check: OK - 472013967360 Bytes Free Space Detected Downloading macOS Installer... Checking for policies triggered by "download-mojave-install" for user "admin"... Executing Policy OS: Move Install App into the right Place Downloading Install macOS Mojave.pkg... Downloading https://svjam001.mutabor.de/JAMFDP/Packages/Install%20macOS%20Mojave.pkg... Installing Install macOS Mojave.pkg... Successfully installed Install macOS Mojave.pkg. Running Recon... Retrieving inventory preferences from https://jamf.mutabor.de:8443/... Finding extension attributes... Locating applications... Locating package receipts... Locating accounts... Searching path: /Applications Locating hard drive information... Locating printers... Locating hardware information (Mac OS X 10.14.2)... Submitting data to https://jamf.mutabor.de:8443/... <computer_id>12</computer_id> Submitting log to https://jamf.mutabor.de:8443/ /Users/Shared/os1014/Install macOS Mojave.app found, checking version. /Library/Application Support/JAMF/tmp/macOS Self Service Upgrade Process Mojave 10.14: line 251: 2524 Terminated: 15 /Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType hud -windowPosition $dlPosition -title "$title" -alignHeading center -alignDescription left -description "$dldescription" -lockHUD -icon "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarDownloadsFolder.icns" -iconSize 100 OSVersion is 10.14.1 Installer found, but old. Deleting... Downloading macOS Installer... Checking for policies triggered by "download-mojave-install" for user "admin"... Executing Policy OS: Move Install App into the right Place Downloading Install macOS Mojave.pkg... Downloading https://svjam001.mutabor.de/JAMFDP/Packages/Install%20macOS%20Mojave.pkg... Installing Install macOS Mojave.pkg... Successfully installed Install macOS Mojave.pkg. Running Recon... Retrieving inventory preferences from https://jamf.mutabor.de:8443/... Finding extension attributes... Locating accounts... Locating applications... Locating hard drive information... Locating printers... Searching path: /Applications Locating package receipts... Locating hardware information (Mac OS X 10.14.2)... Submitting data to https://jamf.mutabor.de:8443/... <computer_id>12</computer_id> Submitting log to https://jamf.mutabor.de:8443/ /Users/Shared/os1014/Install macOS Mojave.app found, checking version. /Library/Application Support/JAMF/tmp/macOS Self Service Upgrade Process Mojave 10.14: line 251: 2890 Terminated: 15 /Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType hud -windowPosition $dlPosition -title "$title" -alignHeading center -alignDescription left -description "$dldescription" -lockHUD -icon "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarDownloadsFolder.icns" -iconSize 100 OSVersion is 10.14.1 Installer found, but old. Deleting... Downloading macOS Installer... Checking for policies triggered by "download-mojave-install" for user "admin"... Executing Policy OS: Move Install App into the right Place Downloading Install macOS Mojave.pkg... Downloading https://svjam001.mutabor.de/JAMFDP/Packages/Install%20macOS%20Mojave.pkg... Installing Install macOS Mojave.pkg... Successfully installed Install macOS Mojave.pkg. Running Recon... Retrieving inventory preferences from https://jamf.mutabor.de:8443/... Finding extension attributes... Locating applications... Searching path: /Applications Locating accounts... Locating printers... Locating hard drive information... Locating package receipts... Locating hardware information (Mac OS X 10.14.2)... Submitting data to https://jamf.mutabor.de:8443/... <computer_id>12</computer_id> Submitting log to https://jamf.mutabor.de:8443/ macOS Installer Downloaded 3 Times - Checksum is Not Valid /Library/Application Support/JAMF/tmp/macOS Self Service Upgrade Process Mojave 10.14: line 258: 3592 Terminated: 15 /Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType hud -windowPosition $dlPosition -title "$title" -alignHeading center -alignDescription left -description "$dldescription" -lockHUD -icon "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarDownloadsFolder.icns" -iconSize 100 Prompting user for error and exiting...

**Comment by AxeKR** [comment]
<img width="449" alt="bildschirmfoto 2019-02-06 um 16 54 42" src="https://user-images.githubusercontent.com/44817288/52354014-eed0c680-2a2f-11e9-8d9c-c9083f65e760.png">

**Comment by AxeKR** [comment]
fp: after changeing the version number 10.14 to 10.14.1 same as the downloaded installer, it is working!
