### ISSUE TITLE
Installer found but old. Deleting...

### ISSUE THREAD

**Issue by LechPoznan86** [kc9wwh/macOSUpgrade#96]
I'm trying to upgrade 10.12.6 client to 10.13.2 High Sierra with the script erroring out saying that “Error Downloading /Applications/Install macOS High Sierra.pkg“ 

As you suggested I set up 2 policies. The one containing the install pkg which is triggered with custom event “download-sierra-install”. This policy runs correctly – I have “Install macOS High Sierra.pkg” being cached then moved to the /Applications folder. This works great however the pkg is soon deleted by the policy/script responsible for installing it. It says the installer is ‘old’. Here are the logs below. 

A highlight portion of the log:
Print: Entry, ":System Image Info:version", Does Not Exist
OSVersion is File Doesn't Exist, Will Create: /Applications/Install macOS High Sierra.pkg/Contents/SharedSupport/InstallInfo.plist
Installer found, but old. Deleting...
Downloading macOS Installer...

Entirety of the log:

Executing Policy Update   OS to 10.13
--
Running script Upgrade   OS...
Script exit code: 0
Script result: Power   Check: OK - AC Power Detected   Disk Check: OK - 482515206144 Bytes Free Space Detected   Downloading macOS Installer...   Checking for policies triggered by "download-sierra-install" for   user "tommy"...   Executing Policy Upgrade OS pt 2   Caching package Install macOS High Sierra.pkg...   Downloading Install macOS High Sierra.pkg...   Downloading https://*******/Install%20macOS%20High%20Sierra.pkg...   Running script OS Move File...   Script exit code: 0   Script result: Copying oS to Users folder      Submitting log to https://*******/   /Applications/Install macOS High Sierra.pkg found, checking version.   /Library/Application Support/JAMF/tmp/Upgrade OS: line 249: 6418 Terminated:   15 /Library/Application\   Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType hud   -windowPosition $dlPosition -title "$title" -alignHeading center -alignDescription   left -description "$dldescription" -lockHUD -icon   "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarDownloadsFolder.icns"   -iconSize 100   Print: Entry, ":System Image Info:version", Does Not Exist   OSVersion is File Doesn't Exist, Will Create: /Applications/Install macOS   High Sierra.pkg/Contents/SharedSupport/InstallInfo.plist   Installer found, but old. Deleting...   Downloading macOS Installer...   Checking for policies triggered by "download-sierra-install" for   user "tommy"...   No policies were found for the "download-sierra-install" trigger.   Downloading macOS Installer...   /Library/Application Support/JAMF/tmp/Upgrade OS: line 142: 6534 Terminated:   15 /Library/Application\ Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper   -windowType hud -windowPosition $dlPosition -title "$title"   -alignHeading center -alignDescription left -description   "$dldescription" -lockHUD -icon   "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarDownloadsFolder.icns"   -iconSize 100   Checking for policies triggered by "download-sierra-install" for   user "tommy"...   No policies were found for the "download-sierra-install" trigger.   macOS Installer Downloaded 3 Times - Checksum is Not Valid   /Library/Application Support/JAMF/tmp/Upgrade OS: line 256: 6624 Terminated:   15 /Library/Application\   Support/JAMF/bin/jamfHelper.app/Contents/MacOS/jamfHelper -windowType hud   -windowPosition $dlPosition -title "$title" -alignHeading center   -alignDescription left -description "$dldescription" -lockHUD -icon   "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarDownloadsFolder.icns"   -iconSize 100   Prompting user for error and exiting...   0
Checking for patches...
No patch policies were   found.

I’m a noob at these things so this might be something simple. Here is a look into my setup. Is this just an issue with the variables set in the JSS?

![image](https://user-images.githubusercontent.com/43278020/54047865-3caf2a80-41a6-11e9-9aa5-8c4d94b89a1b.png)

![image](https://user-images.githubusercontent.com/43278020/54047906-53558180-41a6-11e9-9392-099eec674452.png)

This is the command I’m using to move the pkg from Waiting Room to Applications folder with the “OS package” policy 
#!/bin/sh
echo "Copying oS to Users folder"
cp "/Library/Application Support/JAMF/Waiting Room/Install macOS High Sierra.pkg" "/Applications/"

**Comment by kenchan0130** [comment]
@LechPoznan86 

How about can you change the parameter 4 to`/Applications/Install macOS High Sierra.app`?

You should create a new policy only to download installer like:

<img width="1181" alt="mojave policy" src="https://user-images.githubusercontent.com/1155067/54506066-09c31e80-497e-11e9-8f5d-2982d5704963.png">

and you should split your os installer policy like:

<img width="1184" alt="mojave install" src="https://user-images.githubusercontent.com/1155067/54506192-aeddf700-497e-11e9-82d9-f95dd1b52c2c.png">



(This is an example so it is mojave.)

**Comment by kenchan0130** [comment]
I think this issue is probably resolved.
If you have any problems again, please reopen.
