### ISSUE TITLE
Can you add a API call to JAMF

### ISSUE THREAD

**Issue by kylejericson** [kc9wwh/macOSUpgrade#99]
It would be great to add a API call to the end of this so the device can delete the device record out of jamf. That way the erase install works like the Jamf reset app.

**Comment by kenchan0130** [comment]
> the device can delete the device record out of jamf
I think this case was very special.
Normally, os update is different from new device registration.

The only information we received from you,
I think it is better to create another script and run it if you want.

**Comment by jordan-hamilton** [comment]
Would adding a line to call `/usr/local/bin/jamf flushPolicyHistory` before erasing & installing work for you @kylejericson? The device record would still exist, but all of the computer's once per computer polices would be pending again.

**Comment by kylejericson** [comment]
That may fix the issue.

**Comment by kenchan0130** [comment]
@kylejericson 

Thank you for the update!
Can I close this issue?

**Comment by kylejericson** [comment]
Yes please close.

**Comment by kenchan0130** [comment]
Please let us know if there is a problem again.
